defmodule ExCLI do
  @moduledoc """
  Module containing functions to interact with an application generated by `ExCLI.DSL`
  """

  @doc """
  Process the arguments using the given module, which should be using `ExCLI.DSL`
  """
  @spec process(atom, [String.t], Keyword.t) :: :ok | {:error, any}
  def process(module, args \\ System.argv, options \\ []) do
    app = module.__app__
    IO.inspect(app)
    IO.inspect(args)
    IO.inspect(options)
    :ok
  end
end
